### ISSUE TITLE
TypeError: find() got an unexpected keyword argument 'perform_count'

### ISSUE THREAD

**Issue by mrkafk** [pyeve/eve-sqlalchemy#200]
I'm using following packages from PyPi:

```
Eve==0.9.2
Eve-SQLAlchemy==0.7.1
```
Python 3.7, Debian 9 amd64.

I have cloned the source out and checked out tag `0.7.1`, running `examples/simple` (`python app.py`). Doing:

```
curl -s http://localhost:5000/people
```
results in following exception in server console:

```
127.0.0.1 - - [22/Nov/2019 17:51:22] "GET /people HTTP/1.1" 500 -
Traceback (most recent call last):
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/flaskapp.py", line 1106, in __call__
    return super(Eve, self).__call__(environ, start_response)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/_compat.py", line 39, in reraise
    raise value
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/endpoints.py", line 56, in collections_endpoint
    response = get(resource, lookup)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/methods/common.py", line 318, in rate_limited
    return f(*args, **kwargs)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/auth.py", line 80, in decorated
    return f(*args, **kwargs)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/methods/common.py", line 1354, in decorated
    r = f(resource, **combined_args)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/methods/get.py", line 51, in get
    return get_internal(resource, **lookup)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/methods/get.py", line 125, in get_internal
    return _perform_find(resource, lookup)
  File "/home/mark/projects/nlp_pipeline/venv/lib/python3.7/site-packages/eve/methods/get.py", line 266, in _perform_find
    resource, req, lookup, perform_count=not config.OPTIMIZE_PAGINATION_FOR_SPEED
TypeError: find() got an unexpected keyword argument 'perform_count'

```

**Comment by dkellner** [comment]
You're using Eve-SQLAlchemy with a **not yet supported version of Eve**. Eve-SQLAlchemy 0.7.1 supports `Eve<0.8`, but you are using `Eve==0.9.2`.

Running `pip install .` in Eve-SQLAlchemy's root directory should install the correct dependencies, including `Eve==0.7.10`.
