### ISSUE TITLE
ITEM_LOOKUP_FIELD does not properly inherit its value from ID_FIELD

### ISSUE THREAD

**Issue by dtheodor** [pyeve/eve-sqlalchemy#52]
The ITEM_LOOKUP_FIELD value is retrieved during the `registerSchema` call from the _Eve defaults_, instead of the eve settings you actually pass to the application.

Obviously there is something wrong with the way this is implemented: `registerSchema` apparently needs to be called _before_ the eve application is created and its output is used to fill-in the app settings, so there is no way for it to access the eve application settings which only exist after the app is created (...). The fact that `registerSchema` even tries to access the app configuration is wrong.

Also, I am not sure why you need to retrieve the value of ITEM_LOOKUP_FIELD on schema registration in the first place.

This is also mentioned in issue #42.

**Comment by coriolinus** [comment]
This issue causes errors even in the [trivial example](https://eve-sqlalchemy.readthedocs.org/en/stable/trivial.html) from the documentation: attempting to get a particular resource instance, for example `http://127.0.0.1:5000/people/1`, returns a builtins.AttributeError:

```
Traceback (most recent call last):
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1836, in __call__
    return self.wsgi_app(environ, start_response)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1820, in wsgi_app
    response = self.make_response(self.handle_exception(e))
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1403, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1817, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1477, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1381, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\_compat.py", line 33, in reraise
    raise value
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1475, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\flask\app.py", line 1461, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve\endpoints.py", line 90, in item_endpoint
    response = getitem(resource, **lookup)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve\methods\common.py", line 239, in rate_limited
    return f(*args, **kwargs)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve\auth.py", line 68, in decorated
    return f(*args, **kwargs)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve\methods\common.py", line 820, in decorated
    r = f(resource, **combined_args)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve\methods\get.py", line 196, in getitem
    document = app.data.find_one(resource, req, **lookup)
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve_sqlalchemy\__init__.py", line 190, in find_one
    parse_dictionary(lookup, model))
  File "D:\Users\coriolinus\Documents\Projects\evesqlalchemyexample\lib\site-packages\eve_sqlalchemy\parser.py", line 49, in parse_dictionary
    attr = getattr(model, k)
AttributeError: type object 'People' has no attribute '_id'
```

In theory this should be fixable by patching the settings:

```python
# Primary column name
# Eve follows the Mongo settings by default, and uses '_id'
# In standard SQL, we just use 'id'
# Therefore: 
ID_FIELD = 'id'
ITEM_LOOKUP_FIELD = ID_FIELD
config.ID_FIELD = ID_FIELD
config.ITEM_LOOKUP_FIELD = ID_FIELD
```

However, in practice that doesn't work, and in principle, that shouldn't be necessary; it should happen automatically in Eve-Sqlalchemy's internal configuration defaulting.

**Comment by hroncok** [comment]
I actually needed to do:

    config.ID_FIELD = config.ITEM_LOOKUP_FIELD = 'id'

And:

    domain['people]['id_field'] = config.ID_FIELD 

In order to work with different pk than _id
